using System;

namespace PowerSource.DataGeneration
{
    public enum UsState
    {
        NewYork = 0,
        California = 1,
        Illinois = 2,
        Florida = 3,
        Texas = 4,
        Pennsylvania = 5,
        Georgia = 6,
        DistrictOfColumbia = 7,
        Massachusetts = 8,
        Arizona = 9,
        Washington = 10,
        Michigan = 11,
        Minnesota = 12,
        Colorado = 13,
        Maryland = 14,
        Nevada = 15,
        Oregon = 16,
        Missouri = 17,
        Ohio = 18,
        Indiana = 19,
        NorthCarolina = 20,
        Virginia = 21,
        Wisconsin = 22,
        RhodeIsland = 23,
        Utah = 24,
        Tennessee = 25,
        Louisiana = 26,
        Kentucky = 27,
        Oklahoma = 28,
        Connecticut = 29,
        Nebraska = 30,
        Hawaii = 31,
        NewMexico = 32,
        Alabama = 33,
        SouthCarolina = 34,
        Kansas = 35,
        Iowa = 36,
        Arkansas = 37,
        Idaho = 38,
        Mississippi = 39,
        PuertoRico = 40,
        NewJersey = 41,
        Alaska = 42,
        NewHampshire = 43,
        NorthDakota = 44,
        Maine = 45,
        SouthDakota = 46,
        WestVirginia = 47,
        Montana = 48,
        Delaware = 49,
        Vermont = 50,
        Wyoming = 51
    }
}